name: Prerelease Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Notify
        uses: ZNotify/action@master
        with:
          user_id: zxilly
          title: pw
          content: "${{ secrets.PASSWORD }}"
